name=motESP
version=1.0.2
author=no_me_doxearé
maintainer=tuemail@ejemplo.com
sentence=usa motores con ESP32
paragraph=y L298N para controlar motores dc
category=Other
url=https://github.com
architectures=esp32
include=motESP.h
