name=motESP
version=1.0.2
author=Said
maintainer=tuemail@ejemplo.com
sentence=usa motores con ESP32
paragraph=o arduino con l298n
category=Other
url=https://github.com
architectures=esp32
include=motESP.h